### ISSUE TITLE
[BUG]: rsync error w/ AppleInternal error

### ISSUE THREAD

**Issue by matteobe** [uzh-dqbm-cmi/code-sync#3]
I am trying to syncronize my repository to a folder on leomed but I get the following error:

```
Starting code_sync between /Users/Coding/federated_learning/ and medinfmk:/cluster/dataset/medinfmk/mimicIII/code/ ...
(^C to quit)
rsync: /Users/Coding/federated_learning: invalid numeric value
rsync: /Users/Coding/federated_learning: invalid numeric value
rsync error: syntax or usage error (code 1) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(1337) [client=2.6.9]
rsync error: syntax or usage error (code 1) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(1337) [client=2.6.9]

```

The code_sync command is packaged in a bash file that looks like this: 

```
#!/bin/sh

# Sync code repository with LeoMed
LOCAL_DIR="$(pwd)"
REMOTE_HOST="medinfmk"
REMOTE_PORT=2222
REMOTE_DIR="/cluster/dataset/medinfmk/mimicIII/code"

code_sync --local_dir "$LOCAL_DIR" --remote_dir "$REMOTE_DIR" --target "$REMOTE_HOST" --port $REMOTE_PORT
```

I installed the latest version of code_sync (v0.1.0). 

Did anyone else see this error before? How can I fix it?

**Comment by lokijuhy** [comment]
@matteobe Do you get the same error if you try the `code_sync` command directly, without the bash script setting the variables?

**Comment by lokijuhy** [comment]
@matteobe In terms of debugging, could you add a `print(cmd)` just before the [`subprocess.call(cmd, shell=True)` line](https://github.com/uzh-dqbm-cmi/code-sync/blob/b095e78b16ac0433f7d970ba14f9e6139668ba91/code_sync/code_sync.py#L42) and see if if looks fishy?

**Comment by matteobe** [comment]
> @matteobe Do you get the same error if you try the `code_sync` command directly, without the bash script setting the variables?

Yes, even separately return the same error, was my default way of using it

**Comment by matteobe** [comment]
Update:

Using the Leonhard-mgmt-tools at the commit from last year:
https://github.com/uzh-dqbm-cmi/leonhard-med-mgmt/commit/948297438d29b24548e5713a9ac81f571160a446

works as intended
